### PR TITLE
WIP: Support multiple registries and repositories

### PR DESCRIPTION
**Pull request by nouwaarom**
Towards fixing #105
This is still very much a work in progress but I would like to hear what you think of it.

In order to support multiple registries and be able to download packages from multiple sources I had to change quite a few things.
- An absctraction for registries so that multiple registries can be added. (currently github wiki pages and gitlab files are supported)
- Add extra registries in `clib.json` in a `registries` item.
- Store secrets in `clib_secrets.json` so that we can connect with private registries and repositories
- Make an abstraction for repositories, a repository is a place we can download packages from (currently implemented gitlab and github)

So, what do you think?

### CODE REVIEW

**Comment by jwerle** [comment]
@nouwaarom i can give this a try this afternoon (UTC-4) - I do not know of any clib packages hosted on Gitlab, do you have some instructions that I can use to try this stuff out?

**Comment by nouwaarom** [comment]
Okay, cool. I have been using a private gitlab instance to develop this. I will setup a small demo on gitlab.com now and add some instructions.

**Comment by nouwaarom** [comment]
I create a small demo. It can be found at https://gitlab.com/nouwaarom/clib-demo with some instructions in the readme.
I have developed on ubuntu. I don't know what system you use but I hope it compiles ;)
Please let me know if you have questions or issues.

File: src/registry/registry-manager.c [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+  registry_ptr_t reg;
+  while ((reg = registry_iterator_next(it))) {
+      if (!registry_fetch(reg)) {
+      printf("REGISTRY: could not list packages from. %s\n", registry_get_url(reg));
+    }
+  }
+  registry_iterator_destroy(it);
+}
+
+registry_package_ptr_t registry_manger_find_package(registries_t registries, const char* package_id) {
```
Comment (jwerle) [inline src/registry/registry-manager.c:48]: typo, should be `registry_manager_find_package`

File: src/registry/registry-manager.h [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+registry_ptr_t registry_iterator_next(registry_iterator_t iterator);
+void registry_iterator_destroy(registry_iterator_t iterator);
+
+/**
+ * Search the registry for a package
+ * @param registry a registry handle
+ * @param package_id the identifier of the package "<namespace>/<package_name>"
+ * @return a pointer to the package if it could be found or NULL
+ */
+registry_package_ptr_t registry_manger_find_package(registries_t registries, const char* package_id);
```
Comment (jwerle) [inline src/registry/registry-manager.h:42]: same here

File: src/clib-install.c [hunk 3]
```diff
@@ -298,16 +278,18 @@ static int install_package(const char *slug) {
     }
   }
 
-  if (!pkg) {
-    pkg = clib_package_new_from_slug(slug, opts.verbose);
+  registry_package_ptr_t package_info = registry_manger_find_package(registries, slug);
```
Comment (jwerle) [inline src/clib-install.c:281]: typo, should be `registry_manager_find_package`

**Comment by stephenmathieson** [comment]
This is great! Fantastic work @nouwaarom! Thank you for putting this together.

A PR this big may take some time to review, so please be patient with us. I will try to spend some time testing this out in the next few days.

**Review by jwerle — CHANGES_REQUESTED** [review]

**Comment by jwerle** [comment]
I am very excited for this! I am working through the changes locally now and have some initial notes:

running `clib install .` on the clib-demo project root before moving `clib_secrets.json.dist` to `clib_secrets.json` results in a segfault:

```
 $ clib install .                                                                                                                                                           
       error : Secrets file clib_secrets.json does not exist.
        info : reading local clib.json
Segmentation fault (core dumped)
```

after moving the file, if I run, `clib install .` before setting my personal access token in the file I get:

```
 $ clib install .                                                                                                                                                           
        info : reading local clib.json
REGISTRY: could not list packages from. https://gitlab.com/api/v4/projects/25447829/repository/files/README.md/raw?ref=master
     warning : missing "repo" in  clib.json
     warning : missing repo in clib.json or package.json file for clib-demo
       error : no such file: package.json
```

we should probably have more helpful error messages

after setting the personal access token in the `clibs_secrets.json` file I was able to successful install the dependencies

I echo @stephenmathieson on being patient as this is a big change. Perhaps we can get some tests in this change too?

File: src/registry/registry.c [hunk 4]
```diff
@@ -0,0 +1,164 @@
...
+  registry_ptr_t registry = malloc(sizeof(struct registry_t));
+  registry->url = strdup(url);
+  registry->secret = strdup(secret);
+
+  if (strstr(url, "github.com") != NULL) {
+    registry->type = REGISTRY_TYPE_GITHUB;
+  } else if (strstr(url, "gitlab") != NULL) {
+    registry->type = REGISTRY_TYPE_GITLAB;
+  } else {
+    registry_free(registry);
```
Comment (diasbruno) [inline src/registry/registry.c:65]: Maybe add a warning message that something is wrong?

File: src/repository/gitlab-repository.c [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+//
+// Copyright (c) 2021 Elbert van de Put
+// MIT licensed
+//
+#include "gitlab-repository.h"
+#include <stdio.h>
+#include <stdlib.h>
+#include <string.h>
+#include <url/url.h>
+
```
Comment (diasbruno) [inline src/repository/gitlab-repository.c:12]:
```suggestion

#define GITLAB_API_V4_URL "https://%s/api/v4%s/repository/files/%s/raw?ref=master"

```

File: src/repository/gitlab-repository.c [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+// GET :hostname/api/v4/projects/:id/repository/files/:file_path/raw
+char* gitlab_repository_get_url_for_file(const char*package_url, const char* slug, const char* version, const char *file, const char* secret) {
+  url_data_t *parsed = url_parse(package_url);
+
+  int size = strlen(parsed->hostname) + strlen(parsed->pathname) + strlen(file) + 64;
+  char *url = malloc(size);
+  if (url) {
+    snprintf(url, size, "https://%s/api/v4%s/repository/files/%s/raw?ref=master", parsed->hostname, parsed->pathname, file);
```
Comment (diasbruno) [inline src/repository/gitlab-repository.c:20]:
```suggestion
    snprintf(url, size, GITLAB_API_V4_URL, parsed->hostname, parsed->pathname, file);
```

File: src/registry/github-registry.c [hunk 7]
```diff
@@ -0,0 +1,132 @@
...
+#include "gumbo-get-elements-by-tag-name/get-elements-by-tag-name.h"
+#include "gumbo-text-content/gumbo-text-content.h"
+#include "http-get/http-get.h"
+#include "registry-internal.h"
+#include "strdup/strdup.h"
+#include "substr/substr.h"
+#include "trim/trim.h"
+#include <curl/curl.h>
+#include <string.h>
+
```
Comment (diasbruno) [inline src/registry/github-registry.c:20]:
```suggestion

#define GITHUB_BASE_URL "https://github.com/%s"


```

File: src/registry/github-registry.c [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+/**
+ * Add `href` to the given `package`.
+ */
+static void add_package_href(registry_package_ptr_t self) {
+    size_t len = strlen(self->id) + 20; // https://github.com/ \0
+    self->href = malloc(len);
+    if (self->href)
+        sprintf(self->href, "https://github.com/%s", self->id);
```
Comment (diasbruno) [inline src/registry/github-registry.c:28]:
```suggestion
        sprintf(self->href, GITHUB_BASE_URL, self->id);
```

**Review by diasbruno — COMMENTED** [review]
Hope this suggestions make sense.

File: Makefile [hunk 9]
```diff
@@ -1,4 +1,4 @@
-CC     ?= cc
+CC     ?= gcc
```
[the remark this answers is not in the document]
Comment (nouwaarom) [reply Makefile:1]: No, probably not, I had some compile issues when I started working on this project. This is a leftover from debugging these issues. I will revert this change.

File: Makefile [hunk 10]
```diff
@@ -12,21 +12,22 @@ RM      = rm -f
...
+ALL_SRC = $(wildcard src/*.c src/*.h src/common/*.c src/common/*.h src/registry/*.c src/registry/*.h src/repository/*.h src/repository/*.c test/package/*.c test/cache/*.c)
 SDEPS = $(wildcard deps/*/*.c)
 ODEPS = $(SDEPS:.c=.o)
 DEPS = $(filter-out $(ODEPS), $(SDEPS))
 OBJS = $(DEPS:.c=.o)
-MAKEFILES = $(wildcard deps/*/Makefile)
 
 export CC
 
+CFLAGS  += -std=gnu17 -Ideps -Isrc/common -Isrc/repository -Isrc/registry -g -Wall -Werror=return-type -Wno-unused-function $(shell curl-config --cflags)
```
[the remark this answers is not in the document]
Comment (nouwaarom) [reply Makefile:24]: Yes, I would like that. There is currently an issue because `strdup` is both defined in `deps/strdup/strdup.c` and in `deps/url/url.h` with a `#ifdef _POSIX_C_SOURCE < 200809L` guard. This is because `strdup` is not in the c standard library. I am not sure what the best solution to this problem is. Do you know if it is possible to check if a function is already defined  to prevent multiple definitions?

[the remark this answers is not in the document]
Comment (diasbruno) [reply Makefile:24]: `deps/strdup/strdup.c` is already checking and providing the implementation if not available. Perhaps add its header file (?)

[the remark this answers is not in the document]
Comment (diasbruno) [reply Makefile:24]: But also, let me check if `std=gnu17` can cause problems...

File: Makefile [hunk 11]
```diff
@@ -12,21 +12,22 @@ RM      = rm -f
 MKDIR   = mkdir -p
 
 SRC  = $(wildcard src/*.c)
-COMMON_SRC = $(wildcard src/common/*.c)
-ALL_SRC = $(wildcard src/*.c src/*.h src/common/*.c src/common/*.h test/package/*.c test/cache/*.c)
+COMMON_SRC = $(wildcard src/common/*.c src/registry/*.c src/repository/*)
```
Comment (diasbruno) [inline Makefile:15]:
```suggestion
COMMON_SRC = $(wildcard src/common/*.c src/registry/*.c src/repository/*.c)
```

File: Makefile (hunk 10 above)
[the remark this answers is not in the document]
Comment (diasbruno) [reply Makefile:24]: Well,... it seems that both compiles independently, so both will generate their `strdup` versions. Not sure if `url.c` should required `strdup.c`...

[the remark this answers is not in the document]
Comment (diasbruno) [reply Makefile:24]: `url.c` is not checking if someone else already defined `HAVE_STRDUP`.

File: src/registry/registry.c (hunk 4 above)
Comment (nouwaarom) [reply src/registry/registry.c:71]: I have added a warning, what do you think?

Comment (diasbruno) [reply src/registry/registry.c:71]: Awesome!

File: src/registry/registry-manager.c (hunk 1 above)
Comment (nouwaarom) [reply src/registry/registry-manager.c]: Thanks! I fixed it.

File: Makefile (hunk 10 above)
[the remark this answers is not in the document]
Comment (diasbruno) [reply Makefile]: Submitted [a patch](https://github.com/jwerle/url.h/pull/8) to `url.h` to fix the `strdup` detection.

**Comment by nouwaarom** [comment]
> I echo @stephenmathieson on being patient as this is a big change. Perhaps we can get some tests in this change too?

Yes, I think that adding some tests is a good idea. I am currently working on passing all current tests again because most of them still fail :) After that I will add some tests for the new functionality. What is the current strategy for writing tests?

File: src/repository/gitlab-repository.c [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+// gitlab-repository.c
+//
+// Copyright (c) 2021 Elbert van de Put
+// MIT licensed
+//
+#include "gitlab-repository.h"
+#include <stdio.h>
+#include <stdlib.h>
+#include <string.h>
+#include <url/url.h>
```
Comment (diasbruno) [inline src/repository/gitlab-repository.c:11]:
```suggestion
#include <strdup/strdup.h> // for HAVE_STRDUP
#include <url/url.h>
```

File: Makefile (hunk 10 above)
[the remark this answers is not in the document]
Comment (nouwaarom) [reply Makefile]: We could add something like `#if _POSIX_C_SOURCE < 200809L && !(defined URL_H_NO_STRDUP)
` at `url.h:159`. And define `URL_H_NO_STRDUP` in `url.c`

@jwerle is there a reason that `jwelre/url.h` is header only? Otherwise we might split that into a `url.h` and `url.c` and add `clibs/strdup` as a dependency for it. That would solve our issue with `strdup`

File: src/clib-search.c [hunk 13]
```diff
@@ -16,20 +16,22 @@
...
 #include "strdup/strdup.h"
 #include "tempdir/tempdir.h"
 #include "version.h"
-#include "wiki-registry/wiki-registry.h"
+#include <clib-secrets.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 #include <time.h>
+#include <url/url.h>
```
Comment (diasbruno) [inline src/clib-search.c:29]:
```suggestion
#include <strdup/strdup.h> // for HAVE_STRDUP
#include <url/url.h>
```

File: src/registry/registry.c [hunk 14]
```diff
@@ -0,0 +1,167 @@
...
+// Copyright (c) 2020 clib authors
+// MIT licensed
+//
+
+#include "github-registry.h"
+#include "gitlab-registry.h"
+#include "gumbo-parser/gumbo.h"
+#include "list/list.h"
+#include "registry-internal.h"
+#include "url/url.h"
```
Comment (diasbruno) [inline src/registry/registry.c:13]:
```suggestion
#include <strdup/strdup.h> // for HAVE_STRDUP
#include <url/url.h>
```

File: src/clib-search.c (hunk 13 above)
Comment (diasbruno) [reply src/clib-search.c:29]: This is not going to work...

File: Makefile (hunk 10 above)
[the remark this answers is not in the document]
Comment (jwerle) [reply Makefile]: No real reason anymore we can totally split it up

[the remark this answers is not in the document]
Comment (jwerle) [reply Makefile]: I've accepted the patch and I've released a new version that splits up the source

[the remark this answers is not in the document]
Comment (nouwaarom) [reply Makefile]: Cool, thanks I am using the new version.

File: src/clib-update.c [hunk 15]
```diff
@@ -338,14 +334,14 @@ int main(int argc, char *argv[]) {
...
+  if (package_opts.prefix) {
     char prefix[path_max];
     memset(prefix, 0, path_max);
-    realpath(opts.prefix, prefix);
+    realpath(package_opts.prefix, prefix);
     unsigned long int size = strlen(prefix) + 1;
-    opts.prefix = malloc(size);
-    memset((void *)opts.prefix, 0, size);
-    memcpy((void *)opts.prefix, prefix, size);
+    package_opts.prefix = malloc(size);
```
Comment (diasbruno) [inline src/clib-update.c:342]:
```suggestion
    package_opts.prefix = strndup(prefix, size);
```

File: src/clib-upgrade.c [hunk 16]
```diff
@@ -239,23 +234,23 @@ int main(int argc, char *argv[]) {
     realpath(opts.prefix, prefix);
     unsigned long int size = strlen(prefix) + 1;
     opts.prefix = malloc(size);
```
Comment (diasbruno) [inline src/clib-upgrade.c:236]:
```suggestion
    opts.prefix = strndup(prefix, size);
```

File: src/clib-install.c [hunk 17]
```diff
@@ -426,26 +372,38 @@ int main(int argc, char *argv[]) {
     realpath(opts.prefix, prefix);
     unsigned long int size = strlen(prefix) + 1;
     opts.prefix = malloc(size);
```
Comment (diasbruno) [inline src/clib-install.c:374]:
```suggestion
    opts.prefix = strndup(prefix, size);
```

**Review by stephenmathieson — CHANGES_REQUESTED** [review]
Sorry I haven't been more active here. Been _super_ busy with my 9-5.

I just pulled this branch down and poked around a bit. I got a seg fault doing:

```
make
./clib-install sha1
```

Unfortunately I cleared my terminal buffer, so I don't have the logs 🤷 

I then tried without cache and got an error:

```
/clib-install -c sha1
       fetch : clibs/sha1:package.json
       error : unable to fetch https://raw.githubusercontent.com/clibs/sha1/0.0.1/sha1.h
       error : unable to fetch https://raw.githubusercontent.com/clibs/sha1/0.0.1/sha1.c
➜  clib git:(feature/multiple-registries) ✗
```

I figured it might be something with the `sha1` package, so I tried another:

```
➜  clib git:(feature/multiple-registries) ✗ ./clib-install module
       error : Unable to install package module
➜  clib git:(feature/multiple-registries) ✗
```

I'm not sure what's up, but I am unable to `install` anything using this branch.

**Comment by nouwaarom** [comment]
Hi Stephen. I'm sorry to hear that you could not install those dependencies.
The problem with sha1 is that `package.json` in master specifies that the latest version is `0.0.1` but this tag is missing. (I think we should add an error message saying the last tag is missing.

The problem with module is that it is not listed in a registry. The registry is required to lookup where a package can be downloaded from. (gitlab or github). We could add a fallback to github.com but it is better to just add module to the registry IMHO.

**Review by huuduyentinh14020201 — APPROVED** [review]

**Review by huuduyentinh14020201 — APPROVED** [review]
